name: Test on Maven

on:
  [push, pull_request]

jobs:
  test-1-16:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
         java-version: '8'
         distribution: 'temurin'

      - name: Install GStreamer
        run: sudo apt-get update && sudo apt-get install gstreamer1.0-plugins-good gstreamer1.0-plugins-bad

      - name: Build with Maven
        run: mvn -B verify --file pom.xml

  test-1-20:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
         java-version: '8'
         distribution: 'temurin'

      - name: Install GStreamer
        run: sudo apt-get update && sudo apt-get install gstreamer1.0-plugins-good gstreamer1.0-plugins-bad

      - name: Build with Maven
        run: mvn -B verify --file pom.xml
